name: Test Auto Market Alert

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: pip install pandas yfinance
  
      - name: Set current timestamp
        run: echo "CURRENT_TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Run Python script
        run: python auto_alert.py > alert_list.txt
    
      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: price-alert-artifact
          path: alert_list.txt

  message:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download output artifact
        uses: actions/download-artifact@v2
        with:
          name: price-alert-artifact
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "$(cat price-alert-artifact/alert_list.txt)"
